// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Monika.Models;
using System;

namespace Monika.Discord.Migrations
{
    [DbContext(typeof(MonikaDbContext))]
    [Migration("20171107173055_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Monika.Models.ChatLine", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("ChatLines");
                });

            modelBuilder.Entity("Monika.Models.ChatResponse", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("ChatLineId");

                    b.Property<int>("SupportedChatTypes");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ChatLineId");

                    b.ToTable("ChatResponses");
                });

            modelBuilder.Entity("Monika.Models.ChatTrigger", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("ChatLineId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ChatLineId");

                    b.ToTable("ChatTriggers");
                });

            modelBuilder.Entity("Monika.Models.ChatResponse", b =>
                {
                    b.HasOne("Monika.Models.ChatLine", "ChatLine")
                        .WithMany("Responses")
                        .HasForeignKey("ChatLineId");
                });

            modelBuilder.Entity("Monika.Models.ChatTrigger", b =>
                {
                    b.HasOne("Monika.Models.ChatLine", "ChatLine")
                        .WithMany("Triggers")
                        .HasForeignKey("ChatLineId");
                });
#pragma warning restore 612, 618
        }
    }
}
